baseURL = "https://jjgp.github.io/"
languageCode = "en-us"
title = "Jason Prasad"
theme = "etch"

[params]
  description = "Your siate description"
  copyright = "Copyright © 2022 Jason Prasad"
  dark = "auto"
  highlight = true

[permalinks]
  posts = "/:title/"
